In [1]:
import pandas as pd

In [2]:
trans = pd.read_csv("transaction.csv")

In [3]:
trans.describe()

               time         block
count  2.039147e+08  2.039147e+08
mean   1.507556e+09  4.399263e+06
std    1.528629e+07  9.630437e+05
min    0.000000e+00  0.000000e+00
25%    1.503040e+09  4.172327e+06
50%    1.512968e+09  4.712231e+06
75%    1.517247e+09  4.995088e+06
max    1.523431e+09  5.420000e+06

In [4]:
trans.columns

Index(['from', 'to', 'value', 'time', 'block'], dtype='object')

In [5]:
trans['from'][:5]

0    ethereum
1    ethereum
2    ethereum
3    ethereum
4    ethereum
Name: from, dtype: object

In [9]:
trans[['from','to','value']][trans['from']=='ethereum'][:5]

       from                                        to                value
0  ethereum  0000000000000000000000000000000000000000  5000000000000000000
1  ethereum  05a56e2d52c817161883f50c441c3228cfe54d9f  5000000000000000000
2  ethereum  0193d941b50d91be6567c7ee1c0fe7af498b4137  5000000000000000000
3  ethereum  e6a7a1d47ff21b6321162aea7c6cb457d5476bca  5000000000000000000
4  ethereum  e6a7a1d47ff21b6321162aea7c6cb457d5476bca  5000000000000000000

In [12]:
len(trans['from'].unique())

24111011

In [15]:
len(trans['to'].unique())

27761796

In [14]:
len((trans['from']+trans['to']).unique())

73792000

In [17]:
t = trans[trans['to'] == '05a56e2d52c817161883f50c441c3228cfe54d9f']

In [18]:
len(t)

216

In [21]:
t_1 = trans['to'] == '05a56e2d52c817161883f50c441c3228cfe54d9f'
t_2 = trans['from'] == '05a56e2d52c817161883f50c441c3228cfe54d9f'
t = trans[t_1 | t_2]

In [22]:
t.head()

,from,to,value,time,block
1,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438269988,1
233991,e6a7a1d47ff21b6321162aea7c6cb457d5476bca,05a56e2d52c817161883f50c441c3228cfe54d9f,3625798243899672600,1439885501,105316
385640,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438345912,10797
385727,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438344657,10710
627690,e6a7a1d47ff21b6321162aea7c6cb457d5476bca,05a56e2d52c817161883f50c441c3228cfe54d9f,2889119699486068700,1440011397,112684

In [23]:
len(t)

220

In [24]:
t.sort_values('block')

,from,to,value,time,block
1,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438269988,1
151907632,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438270083,5
10705898,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438270713,235
21721845,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438270943,348
2937024,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438273130,1450
6390292,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438274241,1861
8064897,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438274782,2057
9841705,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438275372,2256
11038995,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438275753,2392
191207772,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438288826,5306
202334791,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438290547,5567
202352375,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438291001,5631
202615940,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438298789,6658
202753137,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438302086,7069
203031153,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438308832,7777
203241299,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438315126,8361
385727,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438344657,10710
385640,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438345912,10797
1272995,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438363888,12113
1272953,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438364416,12155
2289329,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438385529,13662
2422719,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438389134,13899
2624128,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438392636,14133
2624066,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438393685,14195
3245337,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438405973,14948
3580474,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438413467,15398
4111107,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438422577,15972
4206108,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438423879,16047
4206092,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438424203,16063
4763352,ethereum,05a56e2d52c817161883f50c441c3228cfe54d9f,5000000000000000000,1438436423,16769
...,...,...,...,...,...
203052291,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1539297990670840064,1451725547,785271
203057505,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1279989046555046656,1451768732,787827
203066671,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1350457576680171008,1451812254,790429
203072239,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1220263971593637376,1451855340,792966
203081779,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1374468960221542656,1451898309,795507
203091946,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1258987096270797056,1451941466,798082
203096480,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1253305638723779584,1451984602,800601
203164608,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1056949893984499456,1452200531,813253
203169750,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1347095437323347968,1452243769,815836
203180524,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1279067228330061824,1452287032,818423
203188231,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1706860446261624832,1452344606,821837
203196740,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,823223187761620992,1452373315,823524
203208143,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1365791862086443008,1452416586,826050
203213313,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1360486448059217664,1452459719,828596
203223526,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1367718539017513728,1452502855,831182
203228865,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,613319152902600576,1452546215,833764
203240267,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1118671751208308480,1452589269,836210
203246036,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1219672318198660096,1452632487,838703
203262968,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1021879820246387968,1452675712,841055
203269424,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1238357323734068480,1452718931,843662
203280652,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1108273356180679936,1452762149,846142
203285804,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1079642529069955456,1452805390,848750
203296715,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1170752307127196928,1452848464,851291
203301435,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1253158934527032064,1452891667,853861
203312356,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1230683596490124544,1452934835,856336
203316789,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1172246175707763712,1452978209,858922
203328098,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1124704622538813952,1453021371,861400
203333031,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1048754419079278848,1453064471,863901
203343211,52bc44d5378309ee2abf1539bf71de1b7d7be3b5,05a56e2d52c817161883f50c441c3228cfe54d9f,1218819478895413504,1453107658,866526
203904859,05a56e2d52c817161883f50c441c3228cfe54d9f,f94eee144446a9fe6e444dad9f69cd01954c0a34,116146791066933996608,1455384054,998791

In [26]:
trans[trans['from']=='05a56e2d52c817161883f50c441c3228cfe54d9f']

,from,to,value,time,block
107737044,05a56e2d52c817161883f50c441c3228cfe54d9f,1e2683322af6f316a53b6e7e3efd8f605ab2afcf,571485488822856522627,1446414021,475329
107737077,05a56e2d52c817161883f50c441c3228cfe54d9f,1e2683322af6f316a53b6e7e3efd8f605ab2afcf,10000000000000000,1446413541,475307
202925318,05a56e2d52c817161883f50c441c3228cfe54d9f,c130afe98f8c42e19bdacf8c6e63e48a44a26ca8,1,1439399642,75212
203904859,05a56e2d52c817161883f50c441c3228cfe54d9f,f94eee144446a9fe6e444dad9f69cd01954c0a34,116146791066933996608,1455384054,998791

In [39]:
x = t[t['to']=='05a56e2d52c817161883f50c441c3228cfe54d9f']['value']

In [40]:
type(x)

pandas.core.series.Series

In [41]:
x = int(x)

TypeError: cannot convert the series to <class 'int'>

In [42]:
x = pd.to_numeric(x)

ValueError: Integer out of range. at position 108

In [43]:
x = x.astype(float)

In [44]:
x.sum()

6.21397066545064e+20

In [45]:
x.sum()/1000000000000000000

621.397066545064

In [46]:
t['value'] = t['value'].astype(float)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [47]:
t[t['to']=='05a56e2d52c817161883f50c441c3228cfe54d9f']['value'].sum()

6.21397066545064e+20

In [49]:
t[t['from']=='05a56e2d52c817161883f50c441c3228cfe54d9f']['value'].sum()

6.876422798897906e+20

In [50]:
symbols = ['+','-','/','*']

In [52]:
import numpy as np
symbols = np.array(symbols)
symbol_list = symbols[np.random.randint(len(symbols),size = 10000)]

In [53]:
symbol_list

array(['+', '-', '/', ..., '*', '-', '*'], dtype='<U1')

In [54]:
x = np.random.randint(1,11, size=10000)

In [55]:
y = np.random.randint(1,11, size=10000)

In [73]:
def evaluate(x,y,op):
    return eval (str(x) + op + str(y) )

In [75]:
a = np.vectorize(evaluate)

In [76]:
b = np.array([x,y,symbol_list])

In [77]:
a(*b)

array([ 8,  2,  2, ..., 30,  9, 18])

In [60]:
x

array([ 2,  7,  5, ...,  5, 10,  3])

In [61]:
y

array([6, 5, 2, ..., 6, 1, 6])

In [62]:
np.array([x,y,symbol_list])

array([['2', '7', '5', ..., '5', '10', '3'],
       ['6', '5', '2', ..., '6', '1', '6'],
       ['+', '-', '/', ..., '*', '-', '*']], dtype='<U21')

In [74]:
[evaluate(x,y,op) for x,y,op in zip(x,y,symbol_list)]

[8,
 2,
 2.5,
 2.0,
 1.6666666666666667,
 20,
 0.8888888888888888,
 10,
 60,
 5,
 18,
 21,
 1.1111111111111112,
 -4,
 56,
 2.0,
 20,
 4,
 21,
 9,
 11,
 0.6,
 1,
 0.8,
 56,
 72,
 6,
 1,
 15,
 48,
 3.5,
 2,
 50,
 0.5,
 10,
 80,
 12,
 -1,
 0.1111111111111111,
 10,
 14,
 14,
 9,
 25,
 5,
 1.0,
 3,
 6,
 30,
 63,
 2,
 14,
 9,
 1.0,
 18,
 1.0,
 0,
 0.8,
 0.125,
 -8,
 16,
 6,
 2.0,
 10,
 18,
 15,
 4,
 5,
 -5,
 4,
 16,
 -4,
 -3,
 6,
 0,
 4.0,
 32,
 4,
 8,
 15,
 36,
 3,
 1.6666666666666667,
 0.7,
 16,
 20,
 0,
 2,
 12,
 72,
 5,
 56,
 15,
 30,
 30,
 -4,
 13,
 10,
 3,
 4,
 -5,
 0.2857142857142857,
 -2,
 6,
 -4,
 1.0,
 0.8,
 50,
 50,
 11,
 0.2,
 48,
 15,
 -2,
 7,
 50,
 4,
 1.75,
 9,
 1.1111111111111112,
 0.14285714285714285,
 0.625,
 -4,
 0,
 2,
 15,
 12,
 0.16666666666666666,
 6.0,
 50,
 2.0,
 5,
 6,
 -8,
 1.8,
 13,
 90,
 10,
 5,
 -7,
 -5,
 11,
 9,
 0,
 8,
 0.16666666666666666,
 15,
 0.6666666666666666,
 1.0,
 6,
 1.125,
 36,
 -1,
 16,
 1.8,
 -3,
 10.0,
 -2,
 0.125,
 40,
 10,
 18,
 8,
 -7,
 0.5,
 -1,
 -2,
 6,
 9,
 1,
 17,
 9,
 90,
 0.5714285714285714,
 7,
 3.0,
 0.14285714285714285,
 6.0,
 20,
 14,
 -4,
 14,
 50,
 24,
 14,
 7,
 36,
 2,
 -2,
 4,
 4.0,
 0,
 14,
 9,
 -2,
 0,
 13,
 13,
 16,
 -5,
 0.5714285714285714,
 30,
 -1,
 16,
 1,
 -8,
 0.4,
 9,
 10.0,
 -5,
 0.3333333333333333,
 40,
 40,
 20,
 -2,
 4,
 9.0,
 1.0,
 12,
 3,
 14,
 0.8888888888888888,
 0.2,
 1.6666666666666667,
 4,
 -1,
 14,
 -2,
 7,
 70,
 63,
 21,
 0.8333333333333334,
 20,
 8,
 10,
 2.3333333333333335,
 -7,
 1.0,
 7,
 5,
 24,
 17,
 9,
 9,
 0.6666666666666666,
 12,
 13,
 27,
 0.7142857142857143,
 3,
 -3,
 1.1428571428571428,
 6,
 18,
 42,
 2.0,
 40,
 0.5,
 81,
 3,
 2,
 14,
 20,
 0.7777777777777778,
 17,
 11,
 0.9,
 1,
 1.5,
 7,
 50,
 1,
 16,
 70,
 -1,
 7,
 0.7777777777777778,
 1.0,
 8,
 8,
 64,
 1.1666666666666667,
 1.6666666666666667,
 15,
 4,
 -7,
 24,
 18,
 9,
 24,
 12,
 10,
 18,
 9,
 10,
 20,
 1.3333333333333333,
 14,
 16,
 5,
 18,
 13,
 11,
 12,
 -7,
 8,
 1.2,
 11,
 30,
 2.5,
 13,
 56,
 20,
 11,
 4,
 24,
 5,
 50,
 8,
 -5,
 16,
 27,
 18,
 56,
 3,
 4,
 -4,
 0.8,
 8,
 12,
 3,
 3,
 18,
 6,
 6,
 5,
 -3,
 1,
 1.2857142857142858,
 0.75,
 16,
 70,
 80,
 20,
 48,
 12,
 12,
 50,
 5.0,
 12,
 1.0,
 0.14285714285714285,
 -4,
 70,
 1,
 70,
 -8,
 70,
 0.25,
 6,
 35,
 10,
 0.5,
 -1,
 3.3333333333333335,
 7,
 11,
 8,
 5,
 5,
 1,
 14,
 18,
 8,
 10,
 0.6,
 2,
 5,
 10,
 13,
 30,
 5,
 0,
 50,
 72,
 3,
 9,
 24,
 10,
 1.0,
 15,
 8,
 17,
 1,
 7,
 6,
 28,
 12,
 4,
 8,
 19,
 32,
 0.375,
 -3,
 3.0,
 13,
 6,
 -3,
 90,
 3,
 20,
 4,
 45,
 13,
 70,
 -7,
 1.25,
 40,
 -4,
 100,
 7,
 15,
 30,
 32,
 4.0,
 3.3333333333333335,
 25,
 10,
 3,
 2.5,
 -3,
 12,
 0.6666666666666666,
 0.9,
 1.6666666666666667,
 -8,
 48,
 0.4444444444444444,
 0.8571428571428571,
 0.2,
 10,
 0.7,
 9,
 -1,
 80,
 35,
 0.8571428571428571,
 24,
 2,
 -6,
 24,
 2.0,
 13,
 0.5555555555555556,
 30,
 18,
 0.9,
 1,
 3,
 8,
 20,
 -3,
 10,
 0,
 6,
 -8,
 12,
 -4,
 1,
 80,
 17,
 11,
 -1,
 13,
 12,
 5,
 1.4285714285714286,
 9,
 8,
 10,
 7,
 5.0,
 1,
 35,
 1.2857142857142858,
 10,
 63,
 0,
 20,
 7,
 -5,
 5,
 54,
 10,
 1,
 -2,
 40,
 81,
 -1,
 15,
 3,
 12,
 0.4,
 72,
 4,
 18,
 54,
 10,
 0.4,
 0.2857142857142857,
 -6,
 0,
 1.3333333333333333,
 11,
 0.5,
 81,
 -1,
 27,
 72,
 7,
 1.125,
 13,
 1,
 16,
 0.14285714285714285,
 24,
 1.3333333333333333,
 8.0,
 40,
 28,
 3,
 14,
 7,
 13,
 11,
 -5,
 -2,
 -1,
 8,
 2,
 3.5,
 15,
 2.0,
 19,
 -1,
 2.0,
 2,
 81,
 4,
 6,
 -3,
 32,
 9,
 -5,
 12,
 10,
 1.1666666666666667,
 15,
 14,
 90,
 13,
 5,
 9,
 10,
 1,
 10.0,
 36,
 9,
 14,
 0.4,
 12,
 1.75,
 -4,
 1.1666666666666667,
 9,
 19,
 8,
 6,
 7,
 4.0,
 6,
 4,
 14,
 10,
 6.0,
 13,
 18,
 2.3333333333333335,
 3,
 -2,
 40,
 24,
 6,
 20,
 15,
 -1,
 -6,
 0.16666666666666666,
 1.0,
 14,
 0.8333333333333334,
 3,
 14,
 2,
 2,
 2,
 8,
 -4,
 9,
 1,
 0.2222222222222222,
 8,
 9,
 2.25,
 36,
 0.6666666666666666,
 0.9,
 -4,
 40,
 17,
 -4,
 3.0,
 -7,
 2.5,
 0.3,
 0.14285714285714285,
 11,
 63,
 2.25,
 2.25,
 15,
 2.6666666666666665,
 0.6666666666666666,
 2.6666666666666665,
 10,
 0.3,
 20,
 -4,
 5,
 13,
 1,
 6,
 2.0,
 12,
 24,
 12,
 1.3333333333333333,
 35,
 50,
 12,
 35,
 0.6666666666666666,
 72,
 27,
 0.3333333333333333,
 5,
 0,
 20,
 14,
 4,
 4,
 1.5,
 18,
 10,
 0.75,
 4,
 14,
 13,
 0.6,
 50,
 18,
 11,
 0.8888888888888888,
 -2,
 49,
 1.0,
 11,
 -3,
 27,
 -2,
 7,
 0.2,
 1.1111111111111112,
 11,
 3,
 10,
 3,
 0.4,
 0.6666666666666666,
 18,
 6,
 0.5,
 16,
 12,
 0.1,
 49,
 -4,
 42,
 1.0,
 1.2857142857142858,
 12,
 18,
 0.4,
 1.3333333333333333,
 14,
 2,
 8,
 4,
 13,
 6,
 10,
 0.25,
 30,
 7,
 4,
 0.3333333333333333,
 1.3333333333333333,
 0.5,
 32,
 18,
 -5,
 11,
 72,
 0.14285714285714285,
 8,
 20,
 1,
 0,
 11,
 12,
 0,
 6,
 2,
 2.0,
 0.875,
 0.8333333333333334,
 4,
 2.25,
 -3,
 -4,
 4,
 10,
 4.0,
 -2,
 4,
 12,
 6,
 0.1111111111111111,
 9,
 14,
 7,
 72,
 0.6666666666666666,
 0.5,
 24,
 2,
 30,
 -1,
 24,
 9,
 7,
 1.6666666666666667,
 36,
 4,
 8,
 16,
 5,
 4,
 11,
 0.2222222222222222,
 7.0,
 24,
 40,
 2,
 11,
 12,
 2.5,
 -6,
 3,
 1,
 0.8,
 20,
 1,
 0.2,
 2,
 6,
 15,
 4.5,
 0.125,
 -4,
 21,
 5,
 15,
 2.0,
 30,
 18,
 30,
 14,
 2.0,
 4.0,
 18,
 9,
 0.5,
 72,
 2,
 6.0,
 10,
 1.0,
 3.5,
 9,
 -3,
 25,
 40,
 13,
 1.0,
 1,
 54,
 0.5,
 19,
 10,
 0.8,
 4,
 12,
 -7,
 15,
 5,
 12,
 40,
 2,
 2,
 -4,
 -6,
 6,
 12,
 15,
 7,
 8,
 12,
 9,
 50,
 9.0,
 3.0,
 30,
 4.0,
 16,
 1,
 10,
 21,
 30,
 -2,
 48,
 1.0,
 40,
 0.75,
 0.3,
 0.75,
 3.3333333333333335,
 2,
 6,
 1.6,
 12,
 6,
 9,
 11,
 60,
 20,
 0.4,
 5,
 15,
 2.25,
 -3,
 3,
 9,
 10,
 5,
 4,
 5,
 12,
 10,
 5,
 9,
 6,
 12,
 -4,
 21,
 90,
 35,
 20,
 -7,
 -2,
 0.25,
 12,
 0.375,
 8,
 9,
 15,
 1.75,
 8,
 16,
 9,
 2,
 11,
 18,
 60,
 0.5,
 -4,
 3,
 -2,
 6,
 -7,
 5,
 6,
 1.5,
 8,
 -7,
 21,
 12,
 -5,
 -4,
 0.25,
 -2,
 2,
 0.2,
 3,
 6,
 15,
 4,
 -2,
 54,
 -4,
 1,
 14,
 -1,
 50,
 8,
 15,
 14,
 -6,
 16,
 1.8,
 40,
 4,
 1,
 4,
 70,
 5,
 -1,
 5,
 9,
 0,
 0,
 1.1666666666666667,
 7,
 0,
 0.8,
 8,
 -5,
 5,
 2,
 1.3333333333333333,
 9,
 5,
 -5,
 7.0,
 0.3333333333333333,
 0.3333333333333333,
 3,
 6,
 2,
 4,
 28,
 0.8333333333333334,
 4,
 72,
 3.0,
 13,
 0.7,
 2,
 72,
 0.8888888888888888,
 10,
 1.125,
 -6,
 0.5,
 -3,
 12,
 -4,
 3,
 60,
 -6,
 56,
 0.42857142857142855,
 0.25,
 7,
 14,
 1.2857142857142858,
 0.1111111111111111,
 2,
 10,
 ...]

In [72]:
evaluate(1,2,'+')